export const carData = [
  {
    id: 1,
    recommend: 64,
    title: "Mini Cooper",
    likes: 132,
    perhour: 32,
    image: "/mini-cooper.png",
    bgColor: "bg-yellow-100",
  },
  {
    id: 2,
    recommend: 74,
    title: "Swift Suzuki",
    likes: 130,
    perhour: 28,
    image: "/porsche-911.png",
    bgColor: "bg-blue-100",
  },
  {
    id: 3,
    recommend: 84,
    title: "Porsche 911 Carrera",
    likes: 130,
    perhour: 28,
    image: "/mini-cooper.png",
    bgColor: "bg-red-100",
  },
];

export const GuageCardData = [
  {
    id: 1,
    title: "Energy",
    percent: 45,
    iconBgColor: "bg-purple-400",
    background: "#A162F7",
    percentageColor: "#fff",
    image: "/icons/energy.png",
    track: "#B37EFC",
    valueColor: "#fff",
    textColor: "white",
  },
  {
    id: 2,
    title: "Range",
    percent: 65,
    iconBgColor: "bg-red-50",
    background: "#fff",
    percentageColor: "#FF7E86",
    image: "/icons/range.png",
    track: "#F4F5F9",
    textColor: "black",
  },
  {
    id: 3,
    title: "Break fluid",
    percent: 9,
    iconBgColor: "bg-purple-100",
    background: "#fff",
    percentageColor: "#A162F7",
    image: "/icons/break-fluid.png",
    track: "#F4F5F9",
    textColor: "black",
  },
  {
    id: 4,
    title: "Tire Wear",
    percent: 25,
    iconBgColor: "bg-yellow-50",
    background: "#fff",
    percentageColor: "#F6CC0D",
    image: "/icons/tire-wear.png",
    track: "#F4F5F9",
    textColor: "black",
  },
];
