export const BookingData = [
  {
    id: 1,
    bookingTitle: "A1",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 2,
    bookingTitle: "A2",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 3,
    bookingTitle: "A3",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 4,
    bookingTitle: "A4",
    bgcolor: "bg-red-500",
    textcolor: "text-white",
  },
  {
    id: 5,
    bookingTitle: "A5",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 6,
    bookingTitle: "A6",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 7,
    bookingTitle: "A7",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 8,
    bookingTitle: "A8",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 9,
    bookingTitle: "A9",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 10,
    bookingTitle: "A10",
    bgcolor: "bg-red-500",
    textcolor: "text-white",
  },
  {
    id: 11,
    bookingTitle: "B1",
    bgcolor: "bg-red-500",
    textcolor: "text-white",
  },
  {
    id: 12,
    bookingTitle: "B2",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 13,
    bookingTitle: "B3",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 14,
    bookingTitle: "B4",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 15,
    bookingTitle: "B5",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 16,
    bookingTitle: "B6",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 17,
    bookingTitle: "B7",
    bgcolor: "bg-red-500",
    textcolor: "text-white",
  },
  {
    id: 18,
    bookingTitle: "B8",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
  {
    id: 19,
    bookingTitle: "B9",
    bgcolor: "bg-purple-500",
    textcolor: "text-white",
  },
  {
    id: 20,
    bookingTitle: "B10",
    bgcolor: "bg-white",
    textcolor: "text-gray-500",
  },
];

export const carCondition = [
  {
    id: 1,
    title: "Oil Level",
    part: "Engine",
    replace: "Don't Replace",
    level: "80",
    progressColor: "#A162F7",
    image: "/pic1.png",
  },
  {
    id: 2,
    title: "Break Pads",
    part: "Wheels",
    replace: "Still Good",
    level: "70",
    progressColor: "#70CF97",
    image: "/pic2.png",
  },
  {
    id: 3,
    title: "Steering",
    part: "Drivetrain",
    replace: "Need Change",
    level: "55",
    progressColor: "#F6CC0D",
    image: "/pic3.png",
  },
  {
    id: 4,
    title: "Oil Level",
    part: "Engine",
    replace: "Don't Replace",
    level: "80",
    progressColor: "#FF764C",
    image: "/pic1.png",
  },
];
